services:
  db:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER:    myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB:      mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST:     db
      DB_PORT:     "5432"
      DB_USER:     myuser
      DB_PASSWORD: mypass
      DB_NAME:     mydb
    ports:
      - "8080:8080"